
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:8 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "E:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:8 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 2023/12/4 1:12:28。
      节点 1 上的项目“D:\\ogre-git\\ogre\\ogre\\builds\\pugixml-1.14\\CMakeFiles\\3.28.0-rc3\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\ogre-git\\ogre\\ogre\\builds\\pugixml-1.14\\CMakeFiles\\3.28.0-rc3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“D:\\ogre-git\\ogre\\ogre\\builds\\pugixml-1.14\\CMakeFiles\\3.28.0-rc3\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:00.50
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/ogre-git/ogre/ogre/builds/pugixml-1.14/CMakeFiles/3.28.0-rc3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "E:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "E:/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:8 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/ogre-git/ogre/ogre/builds/pugixml-1.14/CMakeFiles/CMakeScratch/TryCompile-1g8816"
      binary: "D:/ogre-git/ogre/ogre/builds/pugixml-1.14/CMakeFiles/CMakeScratch/TryCompile-1g8816"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_POSITION_INDEPENDENT_CODE: "TRUE"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/ogre-git/ogre/ogre/builds/pugixml-1.14/CMakeFiles/CMakeScratch/TryCompile-1g8816'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" cmTC_53cbc.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 2023/12/4 1:12:28。
        节点 1 上的项目“D:\\ogre-git\\ogre\\ogre\\builds\\pugixml-1.14\\CMakeFiles\\CMakeScratch\\TryCompile-1g8816\\cmTC_53cbc.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_53cbc.dir\\Debug\\”。
          正在创建目录“D:\\ogre-git\\ogre\\ogre\\builds\\pugixml-1.14\\CMakeFiles\\CMakeScratch\\TryCompile-1g8816\\Debug\\”。
          正在创建目录“cmTC_53cbc.dir\\Debug\\cmTC_53cbc.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_53cbc.dir\\Debug\\cmTC_53cbc.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_53cbc.dir\\Debug\\\\" /Fd"cmTC_53cbc.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TP /errorReport:queue "E:\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30153 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_53cbc.dir\\Debug\\\\" /Fd"cmTC_53cbc.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TP /errorReport:queue "E:\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\ogre-git\\ogre\\ogre\\builds\\pugixml-1.14\\CMakeFiles\\CMakeScratch\\TryCompile-1g8816\\Debug\\cmTC_53cbc.exe" /INCREMENTAL /ILK:"cmTC_53cbc.dir\\Debug\\cmTC_53cbc.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/ogre-git/ogre/ogre/builds/pugixml-1.14/CMakeFiles/CMakeScratch/TryCompile-1g8816/Debug/cmTC_53cbc.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/ogre-git/ogre/ogre/builds/pugixml-1.14/CMakeFiles/CMakeScratch/TryCompile-1g8816/Debug/cmTC_53cbc.lib" /MACHINE:X64  /machine:x64 cmTC_53cbc.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_53cbc.vcxproj -> D:\\ogre-git\\ogre\\ogre\\builds\\pugixml-1.14\\CMakeFiles\\CMakeScratch\\TryCompile-1g8816\\Debug\\cmTC_53cbc.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_53cbc.dir\\Debug\\cmTC_53cbc.tlog\\unsuccessfulbuild”。
          正在对“cmTC_53cbc.dir\\Debug\\cmTC_53cbc.tlog\\cmTC_53cbc.lastbuildstate”执行 Touch 任务。
        已完成生成项目“D:\\ogre-git\\ogre\\ogre\\builds\\pugixml-1.14\\CMakeFiles\\CMakeScratch\\TryCompile-1g8816\\cmTC_53cbc.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:00.43
        
      exitCode: 0
...
